### ISSUE TITLE
Feedback style

### ISSUE THREAD

**Issue by roberrrt-s** [MohamadAlGhorani/frontend-data#1]
Hi Mohamad, volgens mij ben je begonnen met app.js om ervoor te zorgen dat je applicatie en visualizatie in de eerste plaats werken. Dat is op zich een prima aanpak voor een project van deze omgang, maar toch zou ik graag zelf zien dat je dit bestand in kleinere stukken gaat opdelen. Variabelen als je `const margin` en je `const query` kun je als module importeren zodat je je app.js schoon houdt. Verder ben ik fan van je style, ik snap je naamgeving en kan zelf rustig de code doorlezen en deze begrijpen. Keep it up, en succes deze week.

**Comment by MohamadAlGhorani** [comment]
Hi Robert,

Dankjewel voor je feedback.
Ik ga zeker ervoor zorgen dat alles in orde is en schoon blijft. 😁👍🏻

Groetjes,
Mohamad

**Comment by MohamadAlGhorani** [comment]
Done :D
