### ISSUE TITLE
Sparql query uit ReadMe halen (zet alleen in wiki)

### ISSUE THREAD

**Issue by jenniferslagt** [MohamadAlGhorani/frontend-data#14]
Wat je uit je database haalt is inderdaad belangrijk om in je readme te zetten. Echter is de Sparql query minder interessant voor de gebruiker en kan je deze beter in je wiki houden. Misschien kan je er wel naar verwijzen vanuit je readMe.

**Comment by MohamadAlGhorani** [comment]
Done
